### ISSUE TITLE
Fork electron-handlebars to add templating

### ISSUE THREAD

**Issue by nolangray15** [dlhsiao/code.pyret.org#4]
Fork electron-handlebars, make configurable by specific path and by different extensions than hbs, make CPO depend on our forked version for now, contribute back with PR to original package

**Comment by dlhsiao** [comment]
Forked electron-handlebars, and installed into pyret from the fork. Is throwing `TypeError: mime.lookup is not a function` error currently. Tried installing dependancies separately and reinstalling all modules

**Comment by dlhsiao** [comment]
Error was an issue between Mime 2.x and 1.x. Forcefully installed Mime 1.x. Merged Dana-jarrBranch to horizon.
